### ISSUE TITLE
Technical: fatal error: Array index out of range

### ISSUE THREAD

**Issue by srilatha-sriram** [vipin1006/eHire#32] opened 2016-01-15 07:10 UTC
1.Try to add a new title under 'Rating for technical'
2. Without tabbing  out or clicking elsewhere, click on Add again.
3. App crashes.

**Comment by Tharani-p** [comment] 2016-01-15 08:00
I have fixed the issue.

**Comment by srilatha-sriram** [comment] 2016-01-25 07:11
App still crashes if you remove 'Enter Title' and click on 'Add' again.
Please  perform thorough unit testing before sending a fix for verification.

**Comment by Tharani-p** [comment] 2016-01-25 08:46
I have fixed the issue and committed code.for me its working fine and still you are facing the same problem. let me know.

**Comment by rajeshnath3899** [comment] 2016-01-27 13:39
crash still exists not able to reproduce always

**Comment by Tharani-p** [comment] 2016-01-28 04:32
I will work on it.

**Comment by rajeshnath3899** [comment] 2016-01-28 12:56
padalingam can you also look into this issue ..

**Comment by rajeshnath3899** [comment] 2016-03-03 10:20
issue fixed and verified hence closing this issue

**Closed as completed by rajeshnath3899** 2016-03-03 10:20 UTC
Labels: status:resolved
